---
- name: DEPLOY AS3 DECLARATION
  hosts: localhost
  connection: local
  gather_facts: no

  vars:

    uri_method: POST


  vars_files:
    - /mnt/c/BrunoAlmeida/OneDrive - Version 1/TRAINING/F5/Auto/Project/creds/bigip_creds.yaml
  
  tasks:
  - name: MY AS3 DECLARATION
    uri:
      url: https://3.9.44.205/mgmt/shared/appsvcs/declare
      user: "{{ bigip_user }}"
      password: "{{ bigip_pass }}"
      method: POST
      body: "{{ lookup('file','as3-declaration.json') }}"
      force_basic_auth: yes
      status_code: 200
      body_format: json
      validate_certs: no


